server:
  port: 8090
  servlet:
    context-path: /api/v1

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 7200
  active-timeout: 1800
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true
# 线程池配置
thread:
  pool:
    executor:
      core-pool-size: 20
      max-pool-size: 50
      keep-alive-time: 5000
      block-queue-size: 5000
      policy: CallerRunsPolicy

ai-agent:
  auto:
    enabled: false
    agent-ids:
      - agent-3
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 16379
      database: 0
      connect-timeout: 5000

  #  ai:
  #    #    mcp:
  #    #      client:
  #    #        enabled: true
  #    #        request-timeout: 300s
  #    #        sse:
  #    #          connections:
  #    #            mcp-server:
  #    #              url: http://localhost:8088
  #    openai:
  #      api-key: sk-c58a74e3c645467eab377b01b2b29ce9
  #      embedding:
  #        api-key: sk-fqxfpupthbtjotojseclmfjwplhtzswufmhoyffjfezlssdh
  #        base-url: https://api.siliconflow.cn/
  #        options:
  #          model: BAAI/bge-m3
  #          dimensions: 1024
  #      chat:
  #        api-key: sk-c58a74e3c645467eab377b01b2b29ce9
  #        base-url: https://api.deepseek.com/
  #        options:
  #          model: deepseek-chat
  #          max-tokens: 4096
  #          temperature: 0.6
  #          stream-usage: true

  datasource:
    postgresql:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:15432/ai-agent-station
      username: root
      password: root
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
    mysql:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:13306/ai-agent-station?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
      username: root
      password: root
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
  ai:
    openai:
      api-key: sk-xxs


mybatis:
  config-location: classpath:mybatis-config.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



logging:
  config: classpath:logback-spring.xml
